### ISSUE TITLE
db seed issues

### ISSUE THREAD

**Issue by sapinva** [dchbx/enroll#124]
Rails version        4.2.3
Ruby version         2.3.1-p112 (x86_64-linux)
RubyGems version     2.5.1
Rack version         1.6.4
JavaScript Runtime   therubyracer (V8)

Loading benefit packages.
::: Creating IVL 2015 benefit packages :::
::: Creating IVL 2016 benefit packages :::
rake aborted!
ArgumentError: expected Plan

got around the above by setting the active year to 2015 in the 2016 seed file, but then...

::: Mapping Plans to SBC pdfs seed complete :::
********************************************************************************
updating cost share variance deductibles
rake aborted!
NoMethodError: undefined method `qhp_cost_share_variances' for nil:NilClass

**Comment by Kevin-Wei** [comment]
according to @withintheruins14... "you're going to need some seed files bro"
